_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
EPOCH_LEN:
    value: 1916
