_wandb:
    value:
        cli_version: 0.18.7
        m: []
        python_version: 3.12.2
        t:
            "1":
                - 1
                - 41
                - 55
                - 105
            "2":
                - 1
                - 41
                - 55
                - 105
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.2
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": linux-x86_64
BATCH_SIZE:
    value: 50
BETA1:
    value: 0.98
BETA2:
    value: 0.9
DEVICE:
    value: cuda
EPOCH:
    value: 25
EPOCH_LEN:
    value: 1916
EPS:
    value: 1e-06
EXP_ID:
    value: 0
LOCK:
    value: true
LOCK_TEXT:
    value: false
LOG_DIR:
    value: /home/dazzy/CLIP/Log
LR_GB:
    value: 5e-05
LR_MIN:
    value: 1e-10
LR_REST:
    value: 1e-08
WARMUP_BY_EPOCH:
    value: false
WARMUP_INIT_FACTOR:
    value: 1e-05
WARMUP_MODE:
    value: auto
WARMUP_T:
    value: 1900
WEIGHT_DECAY:
    value: 0.1
